site_name: MIM

nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Algorithm: 'algorithm.md'
  - API: 'api.md'
  - Examples: 'examples.md'

theme:
  name: readthedocs


markdown_extensions:
    - extra
    - tables
    - mdx_math:
        enable_dollar_delimiter: True
    - fenced_code

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
