site_name: MIM

nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - API: 'api.md'
  - Accretion algorithm: 'algorithms/accretion.md'
  - Kernel algorithm: 'algorithms/kernel.md'
  - Examples: 'examples.md'

theme:
  name: mkdocs


markdown_extensions:
    - extra
    - tables
    - mdx_math:
        enable_dollar_delimiter: True
    - fenced_code
theme: readthedocs
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
